### PR TITLE
Completed courses

### PR DESCRIPTION
**Pull request by dhenriquezunosquare**
Each Folder is a Project where i apply differents concepts of Angular

### CODE REVIEW

**Review by alexeikmun — COMMENTED** [review]
Hi @dhenriquezunosquare could give more context of this PR?

**Review by alexeikmun — CHANGES_REQUESTED** [review]
Please provide a README under the root project that explains each course taken with your own words

**Comment by dhenriquezunosquare** [comment]
> Hi @dhenriquezunosquare could give more context of this PR?

This PR has an old Angular course i had done,  and the desing Pattern course i made after the Promotion assesment

**Comment by dhenriquezunosquare** [comment]
> Hi @dhenriquezunosquare could give more context of this PR?

what i would do is "ignore" the angular course, and focus on the desing pattern folder and designpatter commit

https://github.com/Unosquare-CoE-JavaScript/david-henriquez/pull/8/commits/d6c560b8331a7bd8a92035213388975a6cb5d239

**Review by alexeikmun — APPROVED** [review]

**Pull request merged**
